http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["https://10.106.1.122:9200", "https://10.106.1.123:9200", "https://10.106.1.119:9200"]
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "elastic"
xpack.monitoring.elasticsearch.ssl.certificate_authority: /etc/logstash/http_ca.crt
config.reload.automatic: true
config.debug: true
log.level: info
path.logs: /usr/share/logstash/data/logs
pipeline.separate_logs: true
path.data: /usr/share/logstash/data
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 40960mb
path.dead_letter_queue: "/usr/share/logstash/data/dead_letter_queue"

