version: "3.6"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.2
    restart: always
    privileged: true
    ports:
      - 5044:5044
      - 9600:9600
    user: root
    container_name: logstash
    network_mode: host  
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./config/http_ca.crt:/etc/logstash/http_ca.crt
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#      - ./config/jvm.options:/usr/share/logstash/config/jvm.options:ro
#      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
#      - ./config/pipelines/:/usr/share/logstash/pipeline/

